/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.faac;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor Oliveira
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    // Variáveis:
    private String localArq, localArqDiret, localArqSaida;
    private boolean localArqPreenchido, localArqDiretPreenchido, localArqEscolhido;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSetArq = new javax.swing.JButton();
        jlArqEscolhido = new javax.swing.JLabel();
        jlNomeArq = new javax.swing.JLabel();
        jlArqDiretEscolhido = new javax.swing.JLabel();
        jlNomeArqDiret = new javax.swing.JLabel();
        jbGerarRelat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbSetArqDiret = new javax.swing.JButton();
        jlLocalSaida = new javax.swing.JLabel();
        jbLocalSaida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Final");
        setResizable(false);

        jbSetArq.setText("Escolher arquivo principal");
        jbSetArq.setMaximumSize(new java.awt.Dimension(157, 23));
        jbSetArq.setMinimumSize(new java.awt.Dimension(157, 23));
        jbSetArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetArqActionPerformed(evt);
            }
        });

        jlArqEscolhido.setText("Arquivo escolhido:");

        jlArqDiretEscolhido.setText("Local / arquivo escolhido:");

        jbGerarRelat.setText("Gerar relatório de análise");
        jbGerarRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarRelatActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Análise de código fonte");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbSetArqDiret.setText("Escolher arquivo / diretório");
        jbSetArqDiret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetArqDiretActionPerformed(evt);
            }
        });

        jlLocalSaida.setText(" ");

        jbLocalSaida.setText("Escolher local do arquivo de saída");
        jbLocalSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLocalSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbGerarRelat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlArqDiretEscolhido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlNomeArqDiret, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbSetArqDiret)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlArqEscolhido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlNomeArq, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbSetArq, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jlLocalSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jbLocalSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLocalSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlLocalSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jbSetArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlArqEscolhido)
                    .addComponent(jlNomeArq, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbSetArqDiret)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlArqDiretEscolhido)
                    .addComponent(jlNomeArqDiret, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbGerarRelat)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSetArqDiretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetArqDiretActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(
            JFileChooser.FILES_AND_DIRECTORIES);

        int resultado = fileChooser.showOpenDialog(this);

        if(resultado == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File fileName = fileChooser.getSelectedFile();

        if(fileName == null ||
            fileName.getName().equals("")){
            System.out.println("Arquivo inválido.");
        }else if(fileName.isDirectory() ||
            (fileName.isFile() &&  fileName.getName().endsWith(".txt"))){
            this.localArqDiret = fileName.getAbsolutePath();
            this.jlNomeArqDiret.setText(fileName.getName());
            this.localArqDiretPreenchido = true;
        }
    }//GEN-LAST:event_jbSetArqDiretActionPerformed

    private void jbGerarRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarRelatActionPerformed
        // TODO add your handling code here:
        if(this.localArqPreenchido && this.localArqDiretPreenchido
            && this.localArqEscolhido){
            Verificar verificar = new Verificar();
            try {
                verificar.analisar(localArq, localArqDiret, this.localArqSaida);
                JOptionPane.showMessageDialog(null, "Verificação concluída!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbGerarRelatActionPerformed

    private void jbSetArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetArqActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(
            JFileChooser.FILES_ONLY);

        int resultado = fileChooser.showOpenDialog(this);

        if(resultado == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File fileName = fileChooser.getSelectedFile();

        if(fileName == null ||
            fileName.getName().equals("")){
            System.out.println("Arquivo inválido.");
        }else if(fileName.getName().endsWith(".txt")){
            this.localArq = fileName.getAbsolutePath();
            this.jlNomeArq.setText(fileName.getName());
            this.localArqPreenchido = true;
        }
    }//GEN-LAST:event_jbSetArqActionPerformed

    private void jbLocalSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLocalSaidaActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(
            JFileChooser.FILES_AND_DIRECTORIES);

        int resultado = fileChooser.showOpenDialog(this);

        if(resultado == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File fileName = fileChooser.getSelectedFile();
        if(fileName.isDirectory()){
            this.localArqSaida = fileName.getAbsolutePath();
            this.jlLocalSaida.setText("Pasta do arquivo de saída: " + fileName.getName());
            this.localArqEscolhido = true;
        }
    }//GEN-LAST:event_jbLocalSaidaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbGerarRelat;
    private javax.swing.JButton jbLocalSaida;
    private javax.swing.JButton jbSetArq;
    private javax.swing.JButton jbSetArqDiret;
    private javax.swing.JLabel jlArqDiretEscolhido;
    private javax.swing.JLabel jlArqEscolhido;
    private javax.swing.JLabel jlLocalSaida;
    private javax.swing.JLabel jlNomeArq;
    private javax.swing.JLabel jlNomeArqDiret;
    // End of variables declaration//GEN-END:variables
}
